import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Link, useOutletContext } from 'react-router-dom';
import './Profile.css';

const API = 'http://localhost:5000/api/profile';
const serverAsset = (path) => path ? `http://localhost:5000${path}` : null;
const getJson = async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Request failed.'); return data; };

export default function Profile() {
  const { user } = useOutletContext();
  const token = localStorage.getItem('token');
  const headers = { Authorization: `Bearer ${token}` };
  const fileInput = useRef(null);
  const [profile, setProfile] = useState(null);
  const [draft, setDraft] = useState({ name: '', bio: '' });
  const [passwords, setPasswords] = useState({ current_password: '', new_password: '', confirm: '' });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { if (!token) return setLoading(false); try { const data = await getJson(await fetch(API, { headers })); setProfile(data.profile); setDraft({ name: data.profile.name, bio: data.profile.bio || '' }); } catch (err) { setError(err.message); } finally { setLoading(false); } }, [token]);
  useEffect(() => { load(); }, [load]);
  function syncUser(next) { const current = JSON.parse(localStorage.getItem('user') || '{}'); localStorage.setItem('user', JSON.stringify({ ...current, ...next })); window.dispatchEvent(new Event('profile-changed')); }
  async function saveProfile(event) { event.preventDefault(); setSaving(true); setError(''); try { const data = await getJson(await fetch(API, { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify(draft) })); setProfile((current) => ({ ...current, ...data.user })); syncUser(data.user); setNotice('Profile details saved.'); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  async function uploadAvatar(event) { const file = event.target.files?.[0]; if (!file) return; setSaving(true); setError(''); const form = new FormData(); form.append('avatar', file); try { const data = await getJson(await fetch(`${API}/avatar`, { method: 'POST', headers, body: form })); setProfile((current) => ({ ...current, ...data.user })); syncUser(data.user); setNotice('Profile picture updated.'); } catch (err) { setError(err.message); } finally { setSaving(false); event.target.value = ''; } }
  async function changePassword(event) { event.preventDefault(); if (passwords.new_password !== passwords.confirm) return setError('New password and confirmation do not match.'); setSaving(true); setError(''); try { const data = await getJson(await fetch(`${API}/password`, { method: 'PATCH', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify(passwords) })); setPasswords({ current_password: '', new_password: '', confirm: '' }); setNotice(data.message); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  if (!user) return <section className="profile-page"><div className="profile-panel"><h2>MY PROFILE</h2><p>Log in to manage your account.</p><Link to="/login">LOG IN</Link></div></section>;
  if (loading) return <section className="profile-page"><p className="profile-loading">Loading your account workspace...</p></section>;
  if (!profile) return <section className="profile-page"><p className="profile-loading">{error || 'Profile unavailable.'}</p></section>;
  const avatar = serverAsset(profile.avatar_path) || `https://ui-avatars.com/api/?name=${encodeURIComponent(profile.name)}&background=b91522&color=fff&bold=true`;
  const stats = [['RESOURCES', profile.resources_uploaded], ['REVIEWS', profile.reviews_written], ['HELPFUL VOTES', profile.helpful_votes_received], ['TERMS COMPLETE', profile.completed_performance_terms]];
  return <section className="profile-page"><div className="profile-hero"><div className="profile-avatar-wrap"><img src={avatar} alt="Profile" /><button disabled={saving} onClick={() => fileInput.current?.click()}>CHANGE PHOTO</button><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp" onChange={uploadAvatar} /></div><div><p>ACCOUNT WORKSPACE</p><h2>{profile.name}</h2><span>{profile.dept_name} · Batch {profile.batch || '—'} · {profile.role.toUpperCase()}</span></div></div>{error && <div className="profile-message error">{error}</div>}{notice && <div className="profile-message success">{notice}</div>}<div className="profile-stat-grid">{stats.map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><div className="profile-layout"><form className="profile-panel" onSubmit={saveProfile}><p>PERSONAL DETAILS</p><h3>Public profile</h3><label>NAME<input value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} maxLength="255" /></label><label>EMAIL<input value={profile.email} disabled /></label><label>BIO<textarea value={draft.bio} onChange={(e) => setDraft({ ...draft, bio: e.target.value })} maxLength="1000" placeholder="A short introduction for your AcademicOS profile." /></label><small>Your email, batch, department, and role are account-controlled and cannot be changed here.</small><button className="profile-primary" disabled={saving}>{saving ? 'SAVING...' : 'SAVE PROFILE'}</button></form><form className="profile-panel" onSubmit={changePassword}><p>SECURITY</p><h3>Change password</h3><label>CURRENT PASSWORD<input type="password" required minLength="6" value={passwords.current_password} onChange={(e) => setPasswords({ ...passwords, current_password: e.target.value })} /></label><label>NEW PASSWORD<input type="password" required minLength="8" value={passwords.new_password} onChange={(e) => setPasswords({ ...passwords, new_password: e.target.value })} /></label><label>CONFIRM NEW PASSWORD<input type="password" required minLength="8" value={passwords.confirm} onChange={(e) => setPasswords({ ...passwords, confirm: e.target.value })} /></label><small>Use at least 8 characters. Your current password is required before any change.</small><button className="profile-primary" disabled={saving}>{saving ? 'SAVING...' : 'CHANGE PASSWORD'}</button></form></div></section>;
}
