-- AcademicOS performance migration 003
--
-- One-time forward migration for the existing buet_academicos database after
-- migrations 001 and 002. It introduces a CSE curriculum placement model so
-- performance data is term-aware, batch-controlled, and safe for repeated
-- courses such as CSE 400/CSE 450.
--
-- Run with ON_ERROR_STOP enabled. The transaction rolls back completely if a
-- preflight check fails. Do not rerun this migration after it succeeds.

BEGIN;

DO $$
BEGIN
    IF current_database() <> 'buet_academicos' THEN
        RAISE EXCEPTION 'Migration 003 must run on buet_academicos, not %', current_database();
    END IF;

    IF to_regclass('public.users') IS NULL
       OR to_regclass('public.courses') IS NULL
       OR to_regclass('public.user_course_performance') IS NULL THEN
        RAISE EXCEPTION 'Migration 003 requires the schema created by migrations 001 and 002';
    END IF;

    IF to_regclass('public.academic_terms') IS NOT NULL
       OR to_regclass('public.curricula') IS NOT NULL
       OR to_regclass('public.curriculum_courses') IS NOT NULL
       OR to_regclass('public.batch_progress') IS NOT NULL THEN
        RAISE EXCEPTION 'Migration 003 appears to have already been applied; do not run it again';
    END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- 1. Curriculum master data
-- ---------------------------------------------------------------------------

CREATE TABLE public.academic_terms (
    term_code character varying(10) PRIMARY KEY,
    term_order smallint NOT NULL UNIQUE,
    level_no smallint NOT NULL CHECK (level_no BETWEEN 1 AND 4),
    term_no smallint NOT NULL CHECK (term_no BETWEEN 1 AND 2),
    display_name character varying(50) NOT NULL,
    CONSTRAINT academic_terms_code_format_check CHECK (term_code ~ '^[1-4]-[1-2]$'),
    CONSTRAINT academic_terms_order_check CHECK (term_order = ((level_no - 1) * 2 + term_no))
);

CREATE TABLE public.curricula (
    curriculum_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_code character varying(10) NOT NULL,
    curriculum_version character varying(50) NOT NULL,
    name character varying(255) NOT NULL,
    source_title character varying(255),
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT curricula_dept_version_key UNIQUE (dept_code, curriculum_version),
    CONSTRAINT curricula_id_dept_code_key UNIQUE (curriculum_id, dept_code),
    CONSTRAINT curricula_dept_code_fkey
        FOREIGN KEY (dept_code) REFERENCES public.departments(dept_code)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- A curriculum placement is separate from the global course catalogue. The
-- placement ID, rather than course code alone, distinguishes repeat courses
-- in different terms and snapshots the credit used in GPA calculations.
CREATE TABLE public.curriculum_courses (
    curriculum_course_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curriculum_id integer NOT NULL,
    term_code character varying(10) NOT NULL,
    course_code character varying(20) NOT NULL,
    credits_at_placement numeric(3,2) NOT NULL CHECK (credits_at_placement > 0),
    course_type character varying(20) NOT NULL,
    is_required boolean NOT NULL DEFAULT TRUE,
    theory_hours numeric(4,2) NOT NULL DEFAULT 0 CHECK (theory_hours >= 0),
    sessional_hours numeric(4,2) NOT NULL DEFAULT 0 CHECK (sessional_hours >= 0),
    CONSTRAINT curriculum_courses_course_type_check
        CHECK (course_type IN ('theory', 'sessional', 'project', 'thesis', 'other')),
    CONSTRAINT curriculum_courses_unique_placement UNIQUE (curriculum_id, term_code, course_code),
    CONSTRAINT curriculum_courses_curriculum_id_fkey
        FOREIGN KEY (curriculum_id) REFERENCES public.curricula(curriculum_id)
        ON DELETE RESTRICT,
    CONSTRAINT curriculum_courses_term_code_fkey
        FOREIGN KEY (term_code) REFERENCES public.academic_terms(term_code)
        ON DELETE RESTRICT,
    CONSTRAINT curriculum_courses_course_code_fkey
        FOREIGN KEY (course_code) REFERENCES public.courses(course_code)
        ON DELETE RESTRICT
);

-- This is controlled by an administrator: it describes what each batch has
-- completed, rather than guessing from the wall calendar. current_term_code
-- is nullable so a graduated batch can remain at latest_completed = 4-2.
CREATE TABLE public.batch_progress (
    batch_year character varying(4) NOT NULL,
    dept_code character varying(10) NOT NULL,
    curriculum_id integer NOT NULL,
    current_term_code character varying(10),
    latest_completed_term_code character varying(10),
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT batch_progress_pkey PRIMARY KEY (batch_year, dept_code),
    CONSTRAINT batch_progress_batch_year_check CHECK (batch_year ~ '^[0-9]{4}$'),
    CONSTRAINT batch_progress_dept_curriculum_fkey
        FOREIGN KEY (curriculum_id, dept_code)
        REFERENCES public.curricula(curriculum_id, dept_code)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT batch_progress_current_term_code_fkey
        FOREIGN KEY (current_term_code) REFERENCES public.academic_terms(term_code)
        ON DELETE RESTRICT,
    CONSTRAINT batch_progress_latest_completed_term_code_fkey
        FOREIGN KEY (latest_completed_term_code) REFERENCES public.academic_terms(term_code)
        ON DELETE RESTRICT
);

INSERT INTO public.academic_terms (term_code, term_order, level_no, term_no, display_name)
VALUES
    ('1-1', 1, 1, 1, 'Level 1, Term 1'),
    ('1-2', 2, 1, 2, 'Level 1, Term 2'),
    ('2-1', 3, 2, 1, 'Level 2, Term 1'),
    ('2-2', 4, 2, 2, 'Level 2, Term 2'),
    ('3-1', 5, 3, 1, 'Level 3, Term 1'),
    ('3-2', 6, 3, 2, 'Level 3, Term 2'),
    ('4-1', 7, 4, 1, 'Level 4, Term 1'),
    ('4-2', 8, 4, 2, 'Level 4, Term 2');

-- Service-course owners needed by the CSE curriculum. Existing numeric codes
-- for CSE (5), EEE (6), and ME (4) are retained.
INSERT INTO public.departments (dept_code, dept_name)
VALUES
    ('MATH', 'Mathematics'),
    ('PHY', 'Physics'),
    ('CHEM', 'Chemistry'),
    ('HUM', 'Humanities')
ON CONFLICT (dept_code) DO NOTHING;

-- This first version is deliberately defined before legacy UCP migration.
-- It is replaced with the stronger saved-result guard after UCP gets its
-- curriculum_course_id column below.
CREATE OR REPLACE FUNCTION public.validate_batch_progress()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_current_order smallint;
    v_completed_order smallint;
BEGIN
    IF NEW.current_term_code IS NOT NULL THEN
        SELECT term_order INTO v_current_order
        FROM public.academic_terms
        WHERE term_code = NEW.current_term_code;
    END IF;

    IF NEW.latest_completed_term_code IS NOT NULL THEN
        SELECT term_order INTO v_completed_order
        FROM public.academic_terms
        WHERE term_code = NEW.latest_completed_term_code;
    END IF;

    IF NEW.current_term_code IS NOT NULL
       AND NEW.latest_completed_term_code IS NOT NULL
       AND v_completed_order >= v_current_order THEN
        RAISE EXCEPTION 'Latest completed term % must be earlier than current term %',
            NEW.latest_completed_term_code, NEW.current_term_code;
    END IF;

    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_batch_progress
    BEFORE INSERT OR UPDATE ON public.batch_progress
    FOR EACH ROW EXECUTE FUNCTION public.validate_batch_progress();

-- Fixed courses only through Level 3 Term 2. Fourth-year option selections
-- need a separate enrollment design, so this migration intentionally does not
-- invent Option 1–4 records.
CREATE TEMP TABLE cse_curriculum_seed (
    course_code character varying(20) PRIMARY KEY,
    title character varying(255) NOT NULL,
    credits numeric(3,2) NOT NULL,
    term_code character varying(10) NOT NULL,
    dept_code character varying(10) NOT NULL,
    course_type character varying(20) NOT NULL,
    theory_hours numeric(4,2) NOT NULL,
    sessional_hours numeric(4,2) NOT NULL
) ON COMMIT DROP;

INSERT INTO cse_curriculum_seed
    (course_code, title, credits, term_code, dept_code, course_type, theory_hours, sessional_hours)
VALUES
    ('CSE101', 'Structured Programming Language', 3.00, '1-1', '5', 'theory', 3.00, 0.00),
    ('CSE102', 'Structured Programming Language Sessional', 1.50, '1-1', '5', 'sessional', 0.00, 3.00),
    ('CSE103', 'Discrete Mathematics', 3.00, '1-1', '5', 'theory', 3.00, 0.00),
    ('EEE163', 'Introduction to Electrical Engineering', 3.00, '1-1', '6', 'theory', 3.00, 0.00),
    ('EEE164', 'Introduction to Electrical Engineering Sessional', 1.50, '1-1', '6', 'sessional', 0.00, 3.00),
    ('MATH141', 'Calculus I', 3.00, '1-1', 'MATH', 'theory', 3.00, 0.00),
    ('PHY129', 'Structure of Matter, Electricity & Magnetism, Wave Mechanics', 3.00, '1-1', 'PHY', 'theory', 3.00, 0.00),
    ('PHY114', 'Physics Sessional', 1.50, '1-1', 'PHY', 'sessional', 0.00, 3.00),

    ('CSE107', 'Object Oriented Programming Language', 3.00, '1-2', '5', 'theory', 3.00, 0.00),
    ('CSE108', 'Object Oriented Programming Language Sessional', 1.50, '1-2', '5', 'sessional', 0.00, 3.00),
    ('CSE105', 'Data Structures and Algorithms I', 3.00, '1-2', '5', 'theory', 3.00, 0.00),
    ('CSE106', 'Data Structures and Algorithms I Sessional', 1.50, '1-2', '5', 'sessional', 0.00, 3.00),
    ('CHEM113', 'Chemistry', 3.00, '1-2', 'CHEM', 'theory', 3.00, 0.00),
    ('CHEM118', 'Chemistry Sessional', 0.75, '1-2', 'CHEM', 'sessional', 0.00, 1.50),
    ('MATH143', 'Linear Algebra', 3.00, '1-2', 'MATH', 'theory', 3.00, 0.00),
    ('ME165', 'Basic Mechanical Engineering', 3.00, '1-2', '4', 'theory', 3.00, 0.00),
    ('ME174', 'Mechanical Engineering Drawing and CAD', 1.50, '1-2', '4', 'sessional', 0.00, 3.00),

    ('CSE205', 'Digital Logic Design', 3.00, '2-1', '5', 'theory', 3.00, 0.00),
    ('CSE206', 'Digital Logic Design Sessional', 1.50, '2-1', '5', 'sessional', 0.00, 3.00),
    ('CSE207', 'Data Structures and Algorithms II', 3.00, '2-1', '5', 'theory', 3.00, 0.00),
    ('CSE208', 'Data Structures and Algorithms II Sessional', 1.50, '2-1', '5', 'sessional', 0.00, 3.00),
    ('CSE215', 'Database', 3.00, '2-1', '5', 'theory', 3.00, 0.00),
    ('CSE216', 'Database Sessional', 1.50, '2-1', '5', 'sessional', 0.00, 3.00),
    ('EEE263', 'Electronic Circuits', 3.00, '2-1', '6', 'theory', 3.00, 0.00),
    ('EEE264', 'Electronic Circuits Sessional', 1.50, '2-1', '6', 'sessional', 0.00, 3.00),
    ('MATH241', 'Advanced Calculus', 3.00, '2-1', 'MATH', 'theory', 3.00, 0.00),

    ('CSE200', 'Technical Writing and Presentation', 0.75, '2-2', '5', 'other', 0.00, 1.50),
    ('CSE209', 'Computer Architecture', 3.00, '2-2', '5', 'theory', 3.00, 0.00),
    ('CSE210', 'Computer Architecture Sessional', 0.75, '2-2', '5', 'sessional', 0.00, 1.50),
    ('CSE211', 'Theory of Computation', 3.00, '2-2', '5', 'theory', 3.00, 0.00),
    ('CSE213', 'Software Engineering', 3.00, '2-2', '5', 'theory', 3.00, 0.00),
    ('CSE214', 'Software Engineering Sessional', 0.75, '2-2', '5', 'sessional', 0.00, 1.50),
    ('CSE219', 'Signals and Linear Systems', 3.00, '2-2', '5', 'theory', 3.00, 0.00),
    ('CSE220', 'Signals and Linear Systems Sessional', 1.50, '2-2', '5', 'sessional', 0.00, 3.00),
    ('MATH243', 'Probability and Statistics', 3.00, '2-2', 'MATH', 'theory', 3.00, 0.00),

    ('CSE301', 'Mathematics for Computing and Data Science', 3.00, '3-1', '5', 'theory', 3.00, 0.00),
    ('CSE309', 'Compiler', 3.00, '3-1', '5', 'theory', 3.00, 0.00),
    ('CSE310', 'Compiler Sessional', 0.75, '3-1', '5', 'sessional', 0.00, 1.50),
    ('CSE313', 'Operating System', 3.00, '3-1', '5', 'theory', 3.00, 0.00),
    ('CSE314', 'Operating System Sessional', 0.75, '3-1', '5', 'sessional', 0.00, 1.50),
    ('CSE315', 'Microprocessors, Microcontrollers, and Embedded Systems', 3.00, '3-1', '5', 'theory', 3.00, 0.00),
    ('CSE316', 'Microprocessors, Microcontrollers, and Embedded Systems Sessional', 0.75, '3-1', '5', 'sessional', 0.00, 1.50),
    ('CSE317', 'Artificial Intelligence', 3.00, '3-1', '5', 'theory', 3.00, 0.00),
    ('CSE318', 'Artificial Intelligence Sessional', 0.75, '3-1', '5', 'sessional', 0.00, 1.50),

    ('CSE311', 'Data Communication', 3.00, '3-2', '5', 'theory', 3.00, 0.00),
    ('CSE321', 'Computer Networks', 3.00, '3-2', '5', 'theory', 3.00, 0.00),
    ('CSE322', 'Computer Networks Sessional', 1.50, '3-2', '5', 'sessional', 0.00, 3.00),
    ('CSE325', 'Information Systems Development and Management', 3.00, '3-2', '5', 'theory', 3.00, 0.00),
    ('CSE326', 'Information Systems Development and Management Sessional', 1.50, '3-2', '5', 'sessional', 0.00, 3.00),
    ('CSE329', 'Machine Learning', 3.00, '3-2', '5', 'theory', 3.00, 0.00),
    ('CSE330', 'Machine Learning Sessional', 1.50, '3-2', '5', 'sessional', 0.00, 3.00),
    ('CSE450', 'Capstone Project', 1.50, '3-2', '5', 'project', 0.00, 3.00),
    ('HUM347', 'Ethics in Society and E-Governance', 3.00, '3-2', 'HUM', 'theory', 3.00, 0.00);

-- Never overwrite an existing catalogue course silently. A mismatch is safer
-- to investigate than calculating GPA with a different credit/owner.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.courses c
        JOIN cse_curriculum_seed s ON s.course_code = c.course_code
        WHERE c.credits IS DISTINCT FROM s.credits
           OR c.dept_code IS DISTINCT FROM s.dept_code
    ) THEN
        RAISE EXCEPTION 'Existing course catalogue conflicts with the CSE curriculum seed';
    END IF;
END;
$$;

INSERT INTO public.courses (course_code, title, credits, level_term, dept_code)
SELECT course_code, title, credits, term_code, dept_code
FROM cse_curriculum_seed
ON CONFLICT (course_code) DO NOTHING;

INSERT INTO public.curricula (dept_code, curriculum_version, name, source_title)
VALUES ('5', '2023', 'CSE Undergraduate Curriculum 2023', 'Course Info Booklet')
ON CONFLICT (dept_code, curriculum_version) DO NOTHING;

INSERT INTO public.curriculum_courses
    (curriculum_id, term_code, course_code, credits_at_placement, course_type, is_required, theory_hours, sessional_hours)
SELECT
    cu.curriculum_id,
    s.term_code,
    s.course_code,
    s.credits,
    s.course_type,
    TRUE,
    s.theory_hours,
    s.sessional_hours
FROM public.curricula cu
JOIN cse_curriculum_seed s ON TRUE
WHERE cu.dept_code = '5'
  AND cu.curriculum_version = '2023';

-- Batch 2024 is currently studying 2-1, so only 1-1 and 1-2 may be entered.
INSERT INTO public.batch_progress
    (batch_year, dept_code, curriculum_id, current_term_code, latest_completed_term_code)
SELECT '2024', '5', curriculum_id, '2-1', '1-2'
FROM public.curricula
WHERE dept_code = '5' AND curriculum_version = '2023';

-- Imran explicitly authorized removal of this known, incomplete demo result.
-- The exact title guard ensures no real CSE 204 data is touched.
DELETE FROM public.user_course_performance ucp
USING public.courses c
WHERE ucp.course_code = c.course_code
  AND c.course_code = 'CSE204'
  AND c.title = 'CSE 204 (Demo Course)';

UPDATE public.courses
SET archived_at = COALESCE(archived_at, CURRENT_TIMESTAMP)
WHERE course_code = 'CSE204'
  AND title = 'CSE 204 (Demo Course)';

-- ---------------------------------------------------------------------------
-- 2. Upgrade performance rows from course identity to curriculum placement.
-- ---------------------------------------------------------------------------

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.users
        WHERE role = 'student'
          AND (batch IS NULL OR batch !~ '^[0-9]{4}$')
    ) THEN
        RAISE EXCEPTION 'Every student must have a four-digit batch before performance migration';
    END IF;
END;
$$;

ALTER TABLE public.users
    ADD CONSTRAINT users_student_batch_check
    CHECK (role <> 'student' OR (batch IS NOT NULL AND batch ~ '^[0-9]{4}$'));

ALTER TABLE public.user_course_performance
    ADD COLUMN curriculum_course_id integer;

ALTER TABLE public.user_course_performance
    ADD COLUMN created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE public.user_course_performance
    ADD COLUMN updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;

DO $$
DECLARE
    v_invalid_rows integer;
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.user_course_performance
        WHERE grade_point NOT IN (0.00, 2.00, 2.25, 2.50, 2.75, 3.00, 3.25, 3.50, 3.75, 4.00)
    ) THEN
        RAISE EXCEPTION 'Cannot apply the exact BUET grade scale: unsupported legacy grade point found';
    END IF;

    SELECT COUNT(*) INTO v_invalid_rows
    FROM (
        SELECT ucp.user_id, ucp.course_code
        FROM public.user_course_performance ucp
        LEFT JOIN public.users u ON u.user_id = ucp.user_id
        LEFT JOIN public.batch_progress bp
            ON bp.batch_year = u.batch AND bp.dept_code = u.dept_code
        LEFT JOIN public.courses c ON c.course_code = ucp.course_code
        LEFT JOIN public.curriculum_courses cc
            ON cc.curriculum_id = bp.curriculum_id
           AND cc.course_code = ucp.course_code
           AND cc.term_code = c.level_term
        GROUP BY ucp.user_id, ucp.course_code
        HAVING COUNT(cc.curriculum_course_id) <> 1
    ) AS unresolved_rows;

    IF v_invalid_rows > 0 THEN
        RAISE EXCEPTION
            'Cannot migrate % legacy performance row(s): each must resolve to exactly one batch curriculum placement',
            v_invalid_rows;
    END IF;
END;
$$;

UPDATE public.user_course_performance ucp
SET curriculum_course_id = cc.curriculum_course_id
FROM public.users u,
     public.batch_progress bp,
     public.courses c,
     public.curriculum_courses cc
WHERE ucp.user_id = u.user_id
  AND bp.batch_year = u.batch
  AND bp.dept_code = u.dept_code
  AND c.course_code = ucp.course_code
  AND cc.curriculum_id = bp.curriculum_id
  AND cc.course_code = ucp.course_code
  AND cc.term_code = c.level_term;

ALTER TABLE public.user_course_performance
    ALTER COLUMN curriculum_course_id SET NOT NULL;

ALTER TABLE public.user_course_performance
    DROP CONSTRAINT user_course_performance_pkey;

ALTER TABLE public.user_course_performance
    DROP CONSTRAINT ucp_course_code_fkey;

DROP INDEX public.idx_ucp_course_code;

ALTER TABLE public.user_course_performance
    DROP COLUMN course_code;

ALTER TABLE public.user_course_performance
    DROP CONSTRAINT ucp_grade_point_check;

ALTER TABLE public.user_course_performance
    ADD CONSTRAINT ucp_grade_point_check
    CHECK (grade_point IN (0.00, 2.00, 2.25, 2.50, 2.75, 3.00, 3.25, 3.50, 3.75, 4.00));

ALTER TABLE public.user_course_performance
    ADD CONSTRAINT user_course_performance_pkey
    PRIMARY KEY (user_id, curriculum_course_id);

ALTER TABLE public.user_course_performance
    ADD CONSTRAINT ucp_curriculum_course_id_fkey
    FOREIGN KEY (curriculum_course_id)
    REFERENCES public.curriculum_courses(curriculum_course_id)
    ON DELETE RESTRICT;

-- Replacing the early version prevents an admin from moving a batch backwards
-- below results already stored for that batch, or swapping its curriculum.
CREATE OR REPLACE FUNCTION public.validate_batch_progress()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_current_order smallint;
    v_completed_order smallint;
    v_saved_max_order smallint;
BEGIN
    IF NEW.current_term_code IS NOT NULL THEN
        SELECT term_order INTO v_current_order
        FROM public.academic_terms
        WHERE term_code = NEW.current_term_code;
    END IF;

    IF NEW.latest_completed_term_code IS NOT NULL THEN
        SELECT term_order INTO v_completed_order
        FROM public.academic_terms
        WHERE term_code = NEW.latest_completed_term_code;
    END IF;

    IF NEW.current_term_code IS NOT NULL
       AND NEW.latest_completed_term_code IS NOT NULL
       AND v_completed_order >= v_current_order THEN
        RAISE EXCEPTION 'Latest completed term % must be earlier than current term %',
            NEW.latest_completed_term_code, NEW.current_term_code;
    END IF;

    IF TG_OP = 'UPDATE'
       AND NEW.curriculum_id IS DISTINCT FROM OLD.curriculum_id
       AND EXISTS (
           SELECT 1
           FROM public.users u
           JOIN public.user_course_performance ucp ON ucp.user_id = u.user_id
           WHERE u.batch = OLD.batch_year AND u.dept_code = OLD.dept_code
       ) THEN
        RAISE EXCEPTION 'Cannot change a batch curriculum after performance results exist';
    END IF;

    SELECT MAX(at.term_order) INTO v_saved_max_order
    FROM public.users u
    JOIN public.user_course_performance ucp ON ucp.user_id = u.user_id
    JOIN public.curriculum_courses cc ON cc.curriculum_course_id = ucp.curriculum_course_id
    JOIN public.academic_terms at ON at.term_code = cc.term_code
    WHERE u.batch = NEW.batch_year
      AND u.dept_code = NEW.dept_code;

    IF v_saved_max_order IS NOT NULL
       AND v_saved_max_order > COALESCE(v_completed_order, 0) THEN
        RAISE EXCEPTION 'Latest completed term cannot be before an already saved performance result';
    END IF;

    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- The DB remains the final authority even if somebody bypasses React/Express.
CREATE OR REPLACE FUNCTION public.validate_user_course_performance()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_batch_year character varying(20);
    v_dept_code character varying(10);
    v_role character varying(20);
    v_deleted_at timestamp without time zone;
    v_curriculum_id integer;
    v_latest_completed_term character varying(10);
    v_latest_completed_order smallint;
    v_placement_curriculum_id integer;
    v_placement_term character varying(10);
    v_placement_term_order smallint;
    v_is_required boolean;
    v_archived_at timestamp without time zone;
BEGIN
    SELECT batch, dept_code, role, deleted_at
    INTO v_batch_year, v_dept_code, v_role, v_deleted_at
    FROM public.users
    WHERE user_id = NEW.user_id;

    IF NOT FOUND OR v_role <> 'student' OR v_deleted_at IS NOT NULL THEN
        RAISE EXCEPTION 'Only active student accounts can store performance results';
    END IF;

    SELECT curriculum_id, latest_completed_term_code
    INTO v_curriculum_id, v_latest_completed_term
    FROM public.batch_progress
    WHERE batch_year = v_batch_year AND dept_code = v_dept_code;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No batch progression is configured for this student';
    END IF;

    IF v_latest_completed_term IS NULL THEN
        RAISE EXCEPTION 'This batch has no completed term open for result entry';
    END IF;

    SELECT cc.curriculum_id, cc.term_code, at.term_order, cc.is_required, c.archived_at
    INTO v_placement_curriculum_id, v_placement_term, v_placement_term_order, v_is_required, v_archived_at
    FROM public.curriculum_courses cc
    JOIN public.academic_terms at ON at.term_code = cc.term_code
    JOIN public.courses c ON c.course_code = cc.course_code
    WHERE cc.curriculum_course_id = NEW.curriculum_course_id;

    IF NOT FOUND OR v_archived_at IS NOT NULL OR NOT v_is_required THEN
        RAISE EXCEPTION 'The requested curriculum course is not active and required';
    END IF;

    IF v_placement_curriculum_id <> v_curriculum_id THEN
        RAISE EXCEPTION 'The requested course does not belong to this student''s curriculum';
    END IF;

    SELECT term_order INTO v_latest_completed_order
    FROM public.academic_terms
    WHERE term_code = v_latest_completed_term;

    IF v_placement_term_order > v_latest_completed_order THEN
        RAISE EXCEPTION 'Term % is not completed for this batch; latest completed term is %',
            v_placement_term, v_latest_completed_term;
    END IF;

    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_validate_user_course_performance
    BEFORE INSERT OR UPDATE ON public.user_course_performance
    FOR EACH ROW EXECUTE FUNCTION public.validate_user_course_performance();

-- ---------------------------------------------------------------------------
-- 3. Read-only analytics objects for the API and database viva.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.v_student_term_gpa AS
SELECT
    ucp.user_id,
    u.batch AS batch_year,
    u.dept_code,
    cc.curriculum_id,
    cc.term_code,
    COUNT(*)::integer AS recorded_courses,
    SUM(cc.credits_at_placement)::numeric AS recorded_credits,
    ROUND(
        SUM(ucp.grade_point * cc.credits_at_placement)
        / NULLIF(SUM(cc.credits_at_placement), 0),
        2
    ) AS term_gpa
FROM public.user_course_performance ucp
JOIN public.users u ON u.user_id = ucp.user_id
JOIN public.curriculum_courses cc ON cc.curriculum_course_id = ucp.curriculum_course_id
WHERE u.deleted_at IS NULL
GROUP BY ucp.user_id, u.batch, u.dept_code, cc.curriculum_id, cc.term_code;

CREATE OR REPLACE FUNCTION public.get_batch_term_summary(
    p_batch_year character varying,
    p_dept_code character varying,
    p_term_code character varying,
    p_minimum_cohort integer DEFAULT 5
)
RETURNS TABLE (
    registered_students integer,
    expected_courses integer,
    students_with_any_data integer,
    completed_students integer,
    privacy_threshold_met boolean,
    batch_average_gpa numeric,
    median_gpa numeric,
    lowest_gpa numeric,
    highest_gpa numeric,
    standard_deviation_gpa numeric,
    first_quartile_gpa numeric,
    third_quartile_gpa numeric
)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_curriculum_id integer;
    v_latest_completed_term character varying(10);
    v_requested_order smallint;
    v_latest_order smallint;
BEGIN
    IF p_minimum_cohort < 1 THEN
        RAISE EXCEPTION 'Minimum cohort must be at least 1';
    END IF;

    SELECT curriculum_id, latest_completed_term_code
    INTO v_curriculum_id, v_latest_completed_term
    FROM public.batch_progress
    WHERE batch_year = p_batch_year AND dept_code = p_dept_code;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No batch progression is configured for batch % department %', p_batch_year, p_dept_code;
    END IF;

    SELECT term_order INTO v_requested_order
    FROM public.academic_terms WHERE term_code = p_term_code;
    SELECT term_order INTO v_latest_order
    FROM public.academic_terms WHERE term_code = v_latest_completed_term;

    IF v_requested_order IS NULL OR v_latest_order IS NULL OR v_requested_order > v_latest_order THEN
        RAISE EXCEPTION 'Term % is not completed for batch %', p_term_code, p_batch_year;
    END IF;

    RETURN QUERY
    WITH required_courses AS (
        SELECT cc.curriculum_course_id, cc.credits_at_placement
        FROM public.curriculum_courses cc
        JOIN public.courses c ON c.course_code = cc.course_code
        WHERE cc.curriculum_id = v_curriculum_id
          AND cc.term_code = p_term_code
          AND cc.is_required
          AND c.archived_at IS NULL
    ),
    expected AS (
        SELECT COUNT(*)::integer AS expected_courses FROM required_courses
    ),
    active_students AS (
        SELECT user_id
        FROM public.users
        WHERE batch = p_batch_year
          AND dept_code = p_dept_code
          AND role = 'student'
          AND deleted_at IS NULL
    ),
    student_results AS (
        SELECT
            s.user_id,
            COUNT(ucp.curriculum_course_id)::integer AS recorded_courses,
            SUM(ucp.grade_point * rc.credits_at_placement)
                / NULLIF(SUM(rc.credits_at_placement) FILTER (WHERE ucp.curriculum_course_id IS NOT NULL), 0) AS term_gpa
        FROM active_students s
        CROSS JOIN required_courses rc
        LEFT JOIN public.user_course_performance ucp
            ON ucp.user_id = s.user_id
           AND ucp.curriculum_course_id = rc.curriculum_course_id
        GROUP BY s.user_id
    ),
    complete_results AS (
        SELECT sr.term_gpa
        FROM student_results sr
        CROSS JOIN expected e
        WHERE e.expected_courses > 0
          AND sr.recorded_courses = e.expected_courses
    ),
    aggregate_result AS (
        SELECT
            COUNT(*)::integer AS completed_students,
            AVG(term_gpa) AS average_gpa,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY term_gpa) AS median_value,
            MIN(term_gpa) AS lowest_value,
            MAX(term_gpa) AS highest_value,
            stddev_samp(term_gpa) AS stddev_value,
            percentile_cont(0.25) WITHIN GROUP (ORDER BY term_gpa) AS first_quartile_value,
            percentile_cont(0.75) WITHIN GROUP (ORDER BY term_gpa) AS third_quartile_value
        FROM complete_results
    )
    SELECT
        (SELECT COUNT(*)::integer FROM active_students),
        e.expected_courses,
        (SELECT COUNT(*)::integer FROM student_results WHERE recorded_courses > 0),
        a.completed_students,
        a.completed_students >= p_minimum_cohort,
        CASE WHEN a.completed_students >= p_minimum_cohort THEN ROUND(a.average_gpa, 2) END,
        CASE WHEN a.completed_students >= p_minimum_cohort THEN ROUND(a.median_value::numeric, 2) END,
        CASE WHEN a.completed_students >= p_minimum_cohort THEN ROUND(a.lowest_value, 2) END,
        CASE WHEN a.completed_students >= p_minimum_cohort THEN ROUND(a.highest_value, 2) END,
        CASE WHEN a.completed_students >= p_minimum_cohort THEN ROUND(a.stddev_value, 2) END,
        CASE WHEN a.completed_students >= p_minimum_cohort THEN ROUND(a.first_quartile_value::numeric, 2) END,
        CASE WHEN a.completed_students >= p_minimum_cohort THEN ROUND(a.third_quartile_value::numeric, 2) END
    FROM expected e
    CROSS JOIN aggregate_result a;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_batch_term_course_stats(
    p_batch_year character varying,
    p_dept_code character varying,
    p_term_code character varying,
    p_minimum_cohort integer DEFAULT 5
)
RETURNS TABLE (
    curriculum_course_id integer,
    course_code character varying,
    course_title character varying,
    credits numeric,
    completed_students integer,
    privacy_threshold_met boolean,
    average_grade_point numeric,
    median_grade_point numeric,
    pass_rate_percent numeric,
    fail_count integer,
    a_plus_count integer,
    standard_deviation_grade_point numeric
)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_curriculum_id integer;
    v_latest_completed_term character varying(10);
    v_requested_order smallint;
    v_latest_order smallint;
BEGIN
    IF p_minimum_cohort < 1 THEN
        RAISE EXCEPTION 'Minimum cohort must be at least 1';
    END IF;

    SELECT curriculum_id, latest_completed_term_code
    INTO v_curriculum_id, v_latest_completed_term
    FROM public.batch_progress
    WHERE batch_year = p_batch_year AND dept_code = p_dept_code;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'No batch progression is configured for batch % department %', p_batch_year, p_dept_code;
    END IF;

    SELECT term_order INTO v_requested_order FROM public.academic_terms WHERE term_code = p_term_code;
    SELECT term_order INTO v_latest_order FROM public.academic_terms WHERE term_code = v_latest_completed_term;
    IF v_requested_order IS NULL OR v_latest_order IS NULL OR v_requested_order > v_latest_order THEN
        RAISE EXCEPTION 'Term % is not completed for batch %', p_term_code, p_batch_year;
    END IF;

    RETURN QUERY
    WITH required_courses AS (
        SELECT cc.curriculum_course_id, cc.course_code, c.title, cc.credits_at_placement
        FROM public.curriculum_courses cc
        JOIN public.courses c ON c.course_code = cc.course_code
        WHERE cc.curriculum_id = v_curriculum_id
          AND cc.term_code = p_term_code
          AND cc.is_required
          AND c.archived_at IS NULL
    ),
    expected AS (
        SELECT COUNT(*)::integer AS expected_courses FROM required_courses
    ),
    active_students AS (
        SELECT user_id
        FROM public.users
        WHERE batch = p_batch_year AND dept_code = p_dept_code
          AND role = 'student' AND deleted_at IS NULL
    ),
    student_results AS (
        SELECT s.user_id, COUNT(ucp.curriculum_course_id)::integer AS recorded_courses
        FROM active_students s
        CROSS JOIN required_courses rc
        LEFT JOIN public.user_course_performance ucp
            ON ucp.user_id = s.user_id AND ucp.curriculum_course_id = rc.curriculum_course_id
        GROUP BY s.user_id
    ),
    complete_students AS (
        SELECT sr.user_id
        FROM student_results sr CROSS JOIN expected e
        WHERE e.expected_courses > 0 AND sr.recorded_courses = e.expected_courses
    ),
    cohort AS (
        SELECT COUNT(*)::integer AS completed_students FROM complete_students
    ),
    course_aggregate AS (
        SELECT
            rc.curriculum_course_id,
            rc.course_code,
            rc.title,
            rc.credits_at_placement,
            COUNT(ucp.user_id)::integer AS result_count,
            AVG(ucp.grade_point) AS average_value,
            percentile_cont(0.5) WITHIN GROUP (ORDER BY ucp.grade_point) AS median_value,
            100.0 * COUNT(ucp.user_id) FILTER (WHERE ucp.grade_point >= 2.00)
                / NULLIF(COUNT(ucp.user_id), 0) AS pass_rate_value,
            COUNT(ucp.user_id) FILTER (WHERE ucp.grade_point = 0.00)::integer AS fail_value,
            COUNT(ucp.user_id) FILTER (WHERE ucp.grade_point = 4.00)::integer AS a_plus_value,
            stddev_samp(ucp.grade_point) AS stddev_value
        FROM required_courses rc
        LEFT JOIN complete_students cs ON TRUE
        LEFT JOIN public.user_course_performance ucp
            ON ucp.user_id = cs.user_id AND ucp.curriculum_course_id = rc.curriculum_course_id
        GROUP BY rc.curriculum_course_id, rc.course_code, rc.title, rc.credits_at_placement
    )
    SELECT
        ca.curriculum_course_id,
        ca.course_code,
        ca.title,
        ca.credits_at_placement,
        co.completed_students,
        co.completed_students >= p_minimum_cohort,
        CASE WHEN co.completed_students >= p_minimum_cohort THEN ROUND(ca.average_value, 2) END,
        CASE WHEN co.completed_students >= p_minimum_cohort THEN ROUND(ca.median_value::numeric, 2) END,
        CASE WHEN co.completed_students >= p_minimum_cohort THEN ROUND(ca.pass_rate_value, 2) END,
        CASE WHEN co.completed_students >= p_minimum_cohort THEN ca.fail_value END,
        CASE WHEN co.completed_students >= p_minimum_cohort THEN ca.a_plus_value END,
        CASE WHEN co.completed_students >= p_minimum_cohort THEN ROUND(ca.stddev_value, 2) END
    FROM course_aggregate ca
    CROSS JOIN cohort co
    ORDER BY ca.course_code;
END;
$$;

CREATE INDEX idx_curriculum_courses_curriculum_term
    ON public.curriculum_courses(curriculum_id, term_code)
    WHERE is_required;

CREATE INDEX idx_batch_progress_curriculum ON public.batch_progress(curriculum_id);

CREATE INDEX idx_users_batch_dept_active
    ON public.users(batch, dept_code)
    WHERE role = 'student' AND deleted_at IS NULL;

CREATE INDEX idx_ucp_curriculum_course
    ON public.user_course_performance(curriculum_course_id);

-- Final invariant check: every surviving performance row must now be both in
-- its user's curriculum and at or before that batch's completed term.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.user_course_performance ucp
        JOIN public.users u ON u.user_id = ucp.user_id
        JOIN public.batch_progress bp ON bp.batch_year = u.batch AND bp.dept_code = u.dept_code
        JOIN public.curriculum_courses cc ON cc.curriculum_course_id = ucp.curriculum_course_id
        JOIN public.academic_terms result_term ON result_term.term_code = cc.term_code
        LEFT JOIN public.academic_terms completed_term ON completed_term.term_code = bp.latest_completed_term_code
        WHERE cc.curriculum_id <> bp.curriculum_id
           OR completed_term.term_order IS NULL
           OR result_term.term_order > completed_term.term_order
    ) THEN
        RAISE EXCEPTION 'Post-migration performance invariant failed';
    END IF;
END;
$$;

COMMIT;
