-- AcademicOS admin batch-progress migration 004
--
-- One-time forward migration after 003. It makes batch advancement a
-- controlled, auditable transaction and creates real student notifications.
-- Run with ON_ERROR_STOP enabled. Do not rerun after it succeeds.

BEGIN;

DO $$
BEGIN
    IF current_database() <> 'buet_academicos' THEN
        RAISE EXCEPTION 'Migration 004 must run on buet_academicos, not %', current_database();
    END IF;

    IF to_regclass('public.batch_progress') IS NULL
       OR to_regclass('public.academic_terms') IS NULL
       OR to_regclass('public.curricula') IS NULL
       OR to_regclass('public.curriculum_courses') IS NULL
       OR to_regclass('public.notifications') IS NULL
       OR to_regclass('public.users') IS NULL THEN
        RAISE EXCEPTION 'Migration 004 requires migrations 001 through 003';
    END IF;

    IF to_regclass('public.batch_progress_history') IS NOT NULL THEN
        RAISE EXCEPTION 'Migration 004 appears to have already been applied; do not run it again';
    END IF;
END;
$$;

ALTER TABLE public.batch_progress
    ADD COLUMN updated_by_user_id integer;

ALTER TABLE public.batch_progress
    ADD CONSTRAINT batch_progress_updated_by_user_id_fkey
    FOREIGN KEY (updated_by_user_id)
    REFERENCES public.users(user_id)
    ON DELETE SET NULL;

-- Each successful advance gets one immutable audit record. request_id makes a
-- browser retry safe: the same action can never create a second advance.
CREATE TABLE public.batch_progress_history (
    batch_progress_history_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id uuid NOT NULL UNIQUE,
    batch_year character varying(4) NOT NULL,
    dept_code character varying(10) NOT NULL,
    curriculum_id integer NOT NULL,
    previous_current_term_code character varying(10) NOT NULL,
    previous_latest_completed_term_code character varying(10),
    new_current_term_code character varying(10),
    new_latest_completed_term_code character varying(10) NOT NULL,
    advanced_by_user_id integer NOT NULL,
    reason character varying(500) NOT NULL,
    notifications_created integer NOT NULL DEFAULT 0,
    advanced_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT batch_progress_history_batch_year_check CHECK (batch_year ~ '^[0-9]{4}$'),
    CONSTRAINT batch_progress_history_reason_not_blank CHECK (btrim(reason) <> ''),
    CONSTRAINT batch_progress_history_notification_count_check CHECK (notifications_created >= 0),
    CONSTRAINT batch_progress_history_completed_current_check
        CHECK (previous_current_term_code = new_latest_completed_term_code),
    CONSTRAINT batch_progress_history_completed_once_key
        UNIQUE (batch_year, dept_code, new_latest_completed_term_code),
    CONSTRAINT batch_progress_history_curriculum_dept_fkey
        FOREIGN KEY (curriculum_id, dept_code)
        REFERENCES public.curricula(curriculum_id, dept_code)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT batch_progress_history_previous_current_term_fkey
        FOREIGN KEY (previous_current_term_code) REFERENCES public.academic_terms(term_code)
        ON DELETE RESTRICT,
    CONSTRAINT batch_progress_history_previous_completed_term_fkey
        FOREIGN KEY (previous_latest_completed_term_code) REFERENCES public.academic_terms(term_code)
        ON DELETE RESTRICT,
    CONSTRAINT batch_progress_history_new_current_term_fkey
        FOREIGN KEY (new_current_term_code) REFERENCES public.academic_terms(term_code)
        ON DELETE RESTRICT,
    CONSTRAINT batch_progress_history_new_completed_term_fkey
        FOREIGN KEY (new_latest_completed_term_code) REFERENCES public.academic_terms(term_code)
        ON DELETE RESTRICT,
    CONSTRAINT batch_progress_history_advanced_by_user_fkey
        FOREIGN KEY (advanced_by_user_id) REFERENCES public.users(user_id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_batch_progress_history_batch_changed
    ON public.batch_progress_history(batch_year, dept_code, advanced_at DESC);

-- This partial index is exactly what the notification bell needs: one user's
-- unread items, newest first. It avoids scanning their older read history.
CREATE INDEX idx_notifications_unread_recent
    ON public.notifications(user_id, created_at DESC)
    WHERE is_read = FALSE;

CREATE INDEX idx_notifications_batch_progress_history
    ON public.notifications(related_id)
    WHERE type = 'batch_progress_advanced';

-- Strengthen the older progress trigger. It previously blocked backwards
-- movement below saved results, but a direct UPDATE could still skip from
-- 2-1 to 4-1. Term state may now move exactly one legal step at a time.
CREATE OR REPLACE FUNCTION public.validate_batch_progress()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_current_order smallint;
    v_completed_order smallint;
    v_saved_max_order smallint;
    v_expected_next_term character varying(10);
BEGIN
    IF NEW.current_term_code IS NOT NULL THEN
        SELECT term_order INTO v_current_order
        FROM public.academic_terms
        WHERE term_code = NEW.current_term_code;
    END IF;

    IF NEW.latest_completed_term_code IS NOT NULL THEN
        SELECT term_order INTO v_completed_order
        FROM public.academic_terms
        WHERE term_code = NEW.latest_completed_term_code;
    END IF;

    IF NEW.current_term_code IS NOT NULL
       AND NEW.latest_completed_term_code IS NOT NULL
       AND v_completed_order >= v_current_order THEN
        RAISE EXCEPTION USING
            ERRCODE = 'P0001',
            MESSAGE = 'INVALID_BATCH_STATE';
    END IF;

    IF TG_OP = 'UPDATE'
       AND (
           NEW.current_term_code IS DISTINCT FROM OLD.current_term_code
           OR NEW.latest_completed_term_code IS DISTINCT FROM OLD.latest_completed_term_code
       ) THEN
        IF OLD.current_term_code IS NULL THEN
            RAISE EXCEPTION USING
                ERRCODE = 'P0001',
                MESSAGE = 'BATCH_ALREADY_GRADUATED';
        END IF;

        IF NEW.latest_completed_term_code IS DISTINCT FROM OLD.current_term_code THEN
            RAISE EXCEPTION USING
                ERRCODE = 'P0001',
                MESSAGE = 'BATCH_PROGRESS_MUST_COMPLETE_CURRENT_TERM';
        END IF;

        SELECT next_term.term_code INTO v_expected_next_term
        FROM public.academic_terms current_term
        LEFT JOIN public.academic_terms next_term
          ON next_term.term_order = current_term.term_order + 1
        WHERE current_term.term_code = OLD.current_term_code;

        IF v_expected_next_term IS NULL THEN
            IF NEW.current_term_code IS NOT NULL THEN
                RAISE EXCEPTION USING
                    ERRCODE = 'P0001',
                    MESSAGE = 'INVALID_FINAL_TERM_TRANSITION';
            END IF;
        ELSIF NEW.current_term_code IS DISTINCT FROM v_expected_next_term THEN
            RAISE EXCEPTION USING
                ERRCODE = 'P0001',
                MESSAGE = 'BATCH_PROGRESS_MUST_ADVANCE_ONE_TERM';
        END IF;
    END IF;

    IF TG_OP = 'UPDATE'
       AND NEW.curriculum_id IS DISTINCT FROM OLD.curriculum_id
       AND EXISTS (
           SELECT 1
           FROM public.users u
           JOIN public.user_course_performance ucp ON ucp.user_id = u.user_id
           WHERE u.batch = OLD.batch_year AND u.dept_code = OLD.dept_code
       ) THEN
        RAISE EXCEPTION USING
            ERRCODE = 'P0001',
            MESSAGE = 'CANNOT_CHANGE_BATCH_CURRICULUM';
    END IF;

    SELECT MAX(at.term_order) INTO v_saved_max_order
    FROM public.users u
    JOIN public.user_course_performance ucp ON ucp.user_id = u.user_id
    JOIN public.curriculum_courses cc ON cc.curriculum_course_id = ucp.curriculum_course_id
    JOIN public.academic_terms at ON at.term_code = cc.term_code
    WHERE u.batch = NEW.batch_year
      AND u.dept_code = NEW.dept_code;

    IF v_saved_max_order IS NOT NULL
       AND v_saved_max_order > COALESCE(v_completed_order, 0) THEN
        RAISE EXCEPTION USING
            ERRCODE = 'P0001',
            MESSAGE = 'SAVED_RESULTS_REQUIRE_COMPLETED_TERM';
    END IF;

    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- Do not COMMIT inside this procedure. The Node model calls it inside an
-- explicit transaction, so progress + audit + notifications all succeed or
-- all roll back together.
CREATE OR REPLACE PROCEDURE public.advance_batch_progress(
    IN p_actor_user_id integer,
    IN p_batch_year character varying,
    IN p_dept_code character varying,
    IN p_expected_current_term_code character varying,
    IN p_reason text,
    IN p_request_id uuid,
    OUT o_history_id integer,
    OUT o_previous_current_term_code character varying,
    OUT o_new_current_term_code character varying,
    OUT o_latest_completed_term_code character varying,
    OUT o_notifications_created integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_admin_role character varying(20);
    v_admin_deleted_at timestamp without time zone;
    v_curriculum_id integer;
    v_previous_current_term character varying(10);
    v_previous_completed_term character varying(10);
    v_previous_current_order smallint;
    v_new_current_term character varying(10);
    v_new_current_label character varying(50);
    v_notifications_created integer;
    v_existing_history public.batch_progress_history%ROWTYPE;
BEGIN
    IF p_request_id IS NULL THEN
        RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'REQUEST_ID_REQUIRED';
    END IF;

    IF p_reason IS NULL OR btrim(p_reason) = '' OR char_length(p_reason) > 500 THEN
        RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'INVALID_ADVANCE_REASON';
    END IF;

    SELECT role, deleted_at
    INTO v_admin_role, v_admin_deleted_at
    FROM public.users
    WHERE user_id = p_actor_user_id;

    IF NOT FOUND OR v_admin_deleted_at IS NOT NULL OR v_admin_role <> 'admin' THEN
        RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'ACTIVE_ADMIN_REQUIRED';
    END IF;

    SELECT * INTO v_existing_history
    FROM public.batch_progress_history
    WHERE request_id = p_request_id;

    IF FOUND THEN
        IF v_existing_history.batch_year IS DISTINCT FROM p_batch_year
           OR v_existing_history.dept_code IS DISTINCT FROM p_dept_code
           OR v_existing_history.advanced_by_user_id IS DISTINCT FROM p_actor_user_id THEN
            RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'REQUEST_ID_ALREADY_USED';
        END IF;

        o_history_id := v_existing_history.batch_progress_history_id;
        o_previous_current_term_code := v_existing_history.previous_current_term_code;
        o_new_current_term_code := v_existing_history.new_current_term_code;
        o_latest_completed_term_code := v_existing_history.new_latest_completed_term_code;
        o_notifications_created := v_existing_history.notifications_created;
        RETURN;
    END IF;

    SELECT curriculum_id, current_term_code, latest_completed_term_code
    INTO v_curriculum_id, v_previous_current_term, v_previous_completed_term
    FROM public.batch_progress
    WHERE batch_year = p_batch_year
      AND dept_code = p_dept_code
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'BATCH_NOT_CONFIGURED';
    END IF;

    -- Re-check after the row lock: a concurrent request with this same UUID
    -- may have completed while this transaction waited for the batch row.
    SELECT * INTO v_existing_history
    FROM public.batch_progress_history
    WHERE request_id = p_request_id;

    IF FOUND THEN
        IF v_existing_history.batch_year IS DISTINCT FROM p_batch_year
           OR v_existing_history.dept_code IS DISTINCT FROM p_dept_code
           OR v_existing_history.advanced_by_user_id IS DISTINCT FROM p_actor_user_id THEN
            RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'REQUEST_ID_ALREADY_USED';
        END IF;

        o_history_id := v_existing_history.batch_progress_history_id;
        o_previous_current_term_code := v_existing_history.previous_current_term_code;
        o_new_current_term_code := v_existing_history.new_current_term_code;
        o_latest_completed_term_code := v_existing_history.new_latest_completed_term_code;
        o_notifications_created := v_existing_history.notifications_created;
        RETURN;
    END IF;

    IF v_previous_current_term IS NULL THEN
        RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'BATCH_ALREADY_GRADUATED';
    END IF;

    IF p_expected_current_term_code IS DISTINCT FROM v_previous_current_term THEN
        RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'STALE_BATCH_PROGRESS';
    END IF;

    SELECT term_order
    INTO v_previous_current_order
    FROM public.academic_terms
    WHERE term_code = v_previous_current_term;

    SELECT term_code, display_name
    INTO v_new_current_term, v_new_current_label
    FROM public.academic_terms
    WHERE term_order = v_previous_current_order + 1;

    IF v_new_current_term IS NULL AND v_previous_current_term <> '4-2' THEN
        RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'INVALID_FINAL_TERM_TRANSITION';
    END IF;

    -- We do not open a term until the selected curriculum actually defines
    -- courses for it. This prevents a future 4th-year option design from
    -- being guessed or silently exposed.
    IF v_new_current_term IS NOT NULL
       AND NOT EXISTS (
           SELECT 1
           FROM public.curriculum_courses
           WHERE curriculum_id = v_curriculum_id
             AND term_code = v_new_current_term
             AND is_required
       ) THEN
        RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'NEXT_TERM_NOT_CONFIGURED';
    END IF;

    UPDATE public.batch_progress
    SET current_term_code = v_new_current_term,
        latest_completed_term_code = v_previous_current_term,
        updated_by_user_id = p_actor_user_id
    WHERE batch_year = p_batch_year
      AND dept_code = p_dept_code;

    INSERT INTO public.batch_progress_history (
        request_id,
        batch_year,
        dept_code,
        curriculum_id,
        previous_current_term_code,
        previous_latest_completed_term_code,
        new_current_term_code,
        new_latest_completed_term_code,
        advanced_by_user_id,
        reason
    )
    VALUES (
        p_request_id,
        p_batch_year,
        p_dept_code,
        v_curriculum_id,
        v_previous_current_term,
        v_previous_completed_term,
        v_new_current_term,
        v_previous_current_term,
        p_actor_user_id,
        btrim(p_reason)
    )
    RETURNING batch_progress_history_id INTO o_history_id;

    INSERT INTO public.notifications (user_id, type, message, related_id)
    SELECT
        u.user_id,
        'batch_progress_advanced',
        CASE
            WHEN v_new_current_term IS NULL THEN
                format(
                    'Batch %s completed %s. Results can now be entered through %s.',
                    p_batch_year,
                    v_previous_current_term,
                    v_previous_current_term
                )
            ELSE
                format(
                    'Batch %s completed %s and is now in %s. You can enter results through %s.',
                    p_batch_year,
                    v_previous_current_term,
                    v_new_current_label,
                    v_previous_current_term
                )
        END,
        o_history_id
    FROM public.users u
    WHERE u.batch = p_batch_year
      AND u.dept_code = p_dept_code
      AND u.role = 'student'
      AND u.deleted_at IS NULL;

    GET DIAGNOSTICS v_notifications_created = ROW_COUNT;

    UPDATE public.batch_progress_history
    SET notifications_created = v_notifications_created
    WHERE batch_progress_history_id = o_history_id;

    o_previous_current_term_code := v_previous_current_term;
    o_new_current_term_code := v_new_current_term;
    o_latest_completed_term_code := v_previous_current_term;
    o_notifications_created := v_notifications_created;
END;
$$;

COMMIT;
